// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfzykMCDBfbLhB_ejXJ41w2BmT6RGkiuM',
    appId: '1:799516898548:web:723c9961ce513bc7ba9aa1',
    messagingSenderId: '799516898548',
    projectId: 'siviminichat101',
    authDomain: 'siviminichat101.firebaseapp.com',
    storageBucket: 'siviminichat101.firebasestorage.app',
    measurementId: 'G-MMY2HF8QFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFSj_no8koNs3df6J_VWke0_hCM-8p0Co',
    appId: '1:799516898548:android:37c7750e6718eceeba9aa1',
    messagingSenderId: '799516898548',
    projectId: 'siviminichat101',
    storageBucket: 'siviminichat101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMPUv7016yCpAnOkPNaTrIaphnqNNSeD0',
    appId: '1:799516898548:ios:c63aee1ae33de4e5ba9aa1',
    messagingSenderId: '799516898548',
    projectId: 'siviminichat101',
    storageBucket: 'siviminichat101.firebasestorage.app',
    iosBundleId: 'com.sivi.ai.miniChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMPUv7016yCpAnOkPNaTrIaphnqNNSeD0',
    appId: '1:799516898548:ios:c63aee1ae33de4e5ba9aa1',
    messagingSenderId: '799516898548',
    projectId: 'siviminichat101',
    storageBucket: 'siviminichat101.firebasestorage.app',
    iosBundleId: 'com.sivi.ai.miniChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfzykMCDBfbLhB_ejXJ41w2BmT6RGkiuM',
    appId: '1:799516898548:web:fad7b7eb5af61027ba9aa1',
    messagingSenderId: '799516898548',
    projectId: 'siviminichat101',
    authDomain: 'siviminichat101.firebaseapp.com',
    storageBucket: 'siviminichat101.firebasestorage.app',
    measurementId: 'G-7BJNE3G6E4',
  );
}
