// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCki2hh12KM8Q3dDTzJ0_yz9tvYP0Bh6oE',
    appId: '1:101682116148:web:6964263839d041650c3c61',
    messagingSenderId: '101682116148',
    projectId: 'portfolio-42a07',
    authDomain: 'portfolio-42a07.firebaseapp.com',
    storageBucket: 'portfolio-42a07.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQej-3sjePhd7dwZTdxbcrjsc5HPrxa2c',
    appId: '1:101682116148:android:d4125951ce9c017f0c3c61',
    messagingSenderId: '101682116148',
    projectId: 'portfolio-42a07',
    storageBucket: 'portfolio-42a07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvVK73dDIEmSiGyztqf2RpLaCbhX2ECFk',
    appId: '1:101682116148:ios:d909645818189d020c3c61',
    messagingSenderId: '101682116148',
    projectId: 'portfolio-42a07',
    storageBucket: 'portfolio-42a07.firebasestorage.app',
    iosBundleId: 'com.ab.portfolio.baniya.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvVK73dDIEmSiGyztqf2RpLaCbhX2ECFk',
    appId: '1:101682116148:ios:d909645818189d020c3c61',
    messagingSenderId: '101682116148',
    projectId: 'portfolio-42a07',
    storageBucket: 'portfolio-42a07.firebasestorage.app',
    iosBundleId: 'com.ab.portfolio.baniya.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCki2hh12KM8Q3dDTzJ0_yz9tvYP0Bh6oE',
    appId: '1:101682116148:web:5f67c64d09d6e9cb0c3c61',
    messagingSenderId: '101682116148',
    projectId: 'portfolio-42a07',
    authDomain: 'portfolio-42a07.firebaseapp.com',
    storageBucket: 'portfolio-42a07.firebasestorage.app',
  );
}
